apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-data
  namespace: orlok
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clickhouse-db
  name: clickhouse-db
  namespace: orlok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-db
  template:
    metadata:
      labels:
        app: clickhouse-db
    spec:
      volumes:
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-data
      containers:
        - image: 114040874283.dkr.ecr.cn-northwest-1.amazonaws.com.cn/china/generic:clickhouse-server-22.8.8-alpine
          name: clickhouse
          # command: ["/bin/sh"]
          # args:
          #   - '-c'
          #   - >-
          #     echo 'Container started'
          #     clickhouse server &
          #     cat /docker-entrypoint-initdb.d/init.schema | clickhouse-client -mn
          #     fg %1
          ports:
            - containerPort: 8123
              hostPort: 8123
              protocol: TCP
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
          resources:
            limits:
              cpu: 600m
              memory: 4Gi
            requests:
              cpu: 300m
              memory: 2Gi
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: clickhouse-db
  name: clickhouse-db
  namespace: orlok
spec:
  ports:
    - name: "8123"
      port: 8123
      targetPort: 8123
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    app: clickhouse-db
