apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiss-knife-cisco
  namespace: generic
  labels:
    app: swiss-knife-cisco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiss-knife-cisco
  template:
    metadata:
      labels:
        app: swiss-knife-cisco
    spec:
      containers:
        - name: swiss-knife-cisco
          image: 072824598875.dkr.ecr.us-west-2.amazonaws.com/china/generic:swiss-knife
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          volumeMounts:
            - name: swiss-knife-data
              mountPath: /workspace
      volumes:
        - name: swiss-knife-data
          persistentVolumeClaim:
            claimName: swiss-knife-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swiss-knife-data
  namespace: generic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem
